# Generated by Django 4.2.20 on 2025-07-04 17:09

from django.db import migrations, models

import shared.django_apps.rollouts.models


class Migration(migrations.Migration):
    dependencies = [
        ("rollouts", "0006_delete_featureexposure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureflagvariant",
            name="value",
            field=models.JSONField(
                default=shared.django_apps.rollouts.models.ff_value_default,
                help_text="Accepts JSON values. Eg: `true`, `false`, `10`, `['abc', 'def']`, `{'k': 'v'}`",
            ),
        ),
    ]
