repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: uv-lock-shared
        name: uv lock for shared
        entry: tools/devenv/scripts/uv-sync.sh
        files: ^libs/shared/pyproject.toml$
        args: [shared]
        language: script
        types: [file]
      - id: uv-lock-umbrella
        name: uv lock for umbrella
        entry: tools/devenv/scripts/uv-sync.sh
        files: ^pyproject.toml$
        args: [umbrella]
        language: script
        types: [file]
