version: "3"

services:
  # Build the requirements image first
  requirements:
    build:
      context: .
      dockerfile: docker/Dockerfile.requirements
    image: codecov/umbrella-reqs:local

  gateway:
    image: codecov/self-hosted-gateway:latest-stable
    volumes:
      - ./config:/config
      #- ${CODECOV_SSL_CERT-/cert/codecov.crt}:/etc/codecov/ssl/certs/cert.crt:ro # uncomment if using ssl
      - ${CODECOV_SSL_CERT-./cert/nginx-selfsigned.crt}:/etc/codecov/ssl/certs/cert.crt:ro
    ports:
      #- "${CODECOV_PORT-8080}:8080"
      - "${CODECOV_SSL_PORT-443}:8443" # uncomment if using ssl
    environment:
      - CODECOV_GATEWAY_MINIO_ENABLED=true
      - CODECOV_GATEWAY_SSL_ENABLED=true # uncomment if using ssl
    networks:
      - codecov
    depends_on:
      - api
      - frontend

  frontend:
    image: codecov/self-hosted-frontend:latest-stable
    environment:
      - CODECOV_BASE_HOST=codecov.karamba.cloud
      - CODECOV_API_HOST=codecov.karamba.cloud
      - CODECOV_IA_HOST=codecov.karamba.cloud
      - CODECOV_SCHEME=https
    volumes:
      - ./config:/config
    ports:
      - "443"
#      - "8080"
    networks:
      - codecov

  # Build and run API service
  api:
    build:
      context: ./apps/codecov-api
      dockerfile: docker/Dockerfile
      args:
        REQUIREMENTS_IMAGE: codecov/umbrella-reqs:local
        BUILD_ENV: self-hosted
        RELEASE_VERSION: local
    image: codecov/self-hosted-api:latest-calver-oauth2
    volumes:
      - ./config:/config
    networks:
      - codecov
    depends_on:
      - requirements
      - minio
      - timescale
      - postgres
      - redis

  # Build and run Worker service
  worker:
    build:
      context: ./apps/worker
      dockerfile: docker/Dockerfile
      args:
        REQUIREMENTS_IMAGE: codecov/umbrella-reqs:local
        BUILD_ENV: self-hosted-runtime
        RELEASE_VERSION: local
    image: codecov/self-hosted-worker:latest-calver
    environment:
      - RUN_ENV=ENTERPRISE
    volumes:
      - ./config:/config
      - archive-volume:/archive
    networks:
      - codecov
    depends_on:
      - requirements
      - minio
      - redis
      - postgres
      - timescale

  redis:
    image: redis:6.2-alpine
    volumes:
      - redis-volume:/data
    networks:
      - codecov

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - codecov

  timescale:
    image: timescale/timescaledb:latest-pg14
    environment:
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - timescale-volume:/var/lib/postgresql/data
    networks:
      - codecov

  minio:
    image: minio/minio:RELEASE.2020-04-15T00-39-01Z
    command: server /export
    ports:
      - "${CODECOV_MINIO_PORT-9000}:9000"
    environment:
      - MINIO_ACCESS_KEY=codecov-default-key
      - MINIO_SECRET_KEY=codecov-default-secret
    volumes:
      - archive-volume:/export
    networks:
      - codecov

volumes:
  postgres-volume:
  timescale-volume:
  redis-volume:
  archive-volume:

networks:
  codecov:
    driver: bridge
