# Generated by Django 4.2.20 on 2025-05-21 21:16

from django.db import migrations, models

from shared.django_apps.codecov_auth.migrations.migration_helpers import (
    backfill_app_id,
)


def backfill_app_id_helper(apps, schema):
    GithubAppInstallation = apps.get_model("codecov_auth", "GithubAppInstallation")
    backfill_app_id(model=GithubAppInstallation)


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_auth", "0066_add_pro_plan"),
    ]

    operations = [
        migrations.RunPython(
            backfill_app_id_helper,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="githubappinstallation",
            name="app_id",
            field=models.IntegerField(),
        ),
    ]
