# Generated by Django 4.2.20 on 2025-05-28 23:57

from django.db import migrations

from shared.django_apps.codecov_auth.migrations.migration_helpers import (
    eliminate_dupes,
)


def eliminate_dupes_helper(apps, schema):
    GithubAppInstallation = apps.get_model("codecov_auth", "GithubAppInstallation")
    eliminate_dupes(model=GithubAppInstallation)


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_auth", "0067_alter_githubappinstallation_app_id"),
    ]

    operations = [
        migrations.RunPython(
            eliminate_dupes_helper,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterUniqueTogether(
            name="githubappinstallation",
            unique_together={("app_id", "installation_id")},
        ),
    ]
