# Generated by Django 4.2.21 on 2025-06-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_auth", "0068_alter_githubappinstallation_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="sentry_org_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="plan",
            field=models.CharField(
                choices=[
                    ("users-basic", "BASIC_PLAN_NAME"),
                    ("users-trial", "TRIAL_PLAN_NAME"),
                    ("users-pr-inappm", "CODECOV_PRO_MONTHLY"),
                    ("users-pr-inappy", "CODECOV_PRO_YEARLY"),
                    ("users-sentrym", "SENTRY_MONTHLY"),
                    ("users-sentryy", "SENTRY_YEARLY"),
                    ("users-teamm", "TEAM_MONTHLY"),
                    ("users-teamy", "TEAM_YEARLY"),
                    ("users", "GHM_PLAN_NAME"),
                    ("users-free", "FREE_PLAN_NAME"),
                    ("users-inappm", "CODECOV_PRO_MONTHLY_LEGACY"),
                    ("users-inappy", "CODECOV_PRO_YEARLY_LEGACY"),
                    ("users-enterprisem", "ENTERPRISE_CLOUD_MONTHLY"),
                    ("users-enterprisey", "ENTERPRISE_CLOUD_YEARLY"),
                    ("users-developer", "USERS_DEVELOPER"),
                    ("sentry-merge", "SENTRY_MERGE_PLAN"),
                ],
                default="users-developer",
                max_length=50,
            ),
        ),
    ]
