# Generated by Django 4.2.21 on 2025-06-26 18:12

from django.db import migrations

from shared.django_apps.migration_utils import RiskyRunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_auth", "0069_account_sentry_org_id_alter_account_plan"),
    ]

    operations = [
        RiskyRunSQL(
            "ALTER TYPE plans ADD VALUE 'sentry-merge';",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
