# Generated by Django 4.2.20 on 2025-07-03 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_auth", "0070_add_sentry_merge_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicebilling",
            name="account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_billing",
                to="codecov_auth.account",
            ),
        ),
        migrations.AlterField(
            model_name="stripebilling",
            name="account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stripe_billing",
                to="codecov_auth.account",
            ),
        ),
    ]
