# Generated by Django 4.2.20 on 2025-07-04 19:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timeseries", "0019_testrun_real_time_agg"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Testrun",
        ),
        migrations.DeleteModel(
            name="TestrunBranchSummary",
        ),
        migrations.DeleteModel(
            name="TestrunSummary",
        ),
    ]
