# Generated by Django 4.2.20 on 2025-07-02 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("labelanalysis", "0003_labelanalysisprocessingerror"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="labelanalysisprocessingerror",
            table="labelanalysis_labelanalysisprocessingerror",
        ),
        migrations.AlterModelTable(
            name="labelanalysisrequest",
            table="labelanalysis_labelanalysisrequest",
        ),
    ]
