TEST_YML := ../../tools/devenv/config/test.yml

# Optional EXTRA_PYTEST_ARGS variable to specify pytest path
EXTRA_PYTEST_ARGS ?=

.PHONY: devenv.test
devenv.test: devenv.test.worker devenv.test.api devenv.test.shared

.PHONY: devenv.test.worker
devenv.test.worker:
	docker exec -e COVERAGE_CORE=sysmon -e RUN_ENV=TESTING -e CODECOV_YML=${TEST_YML} -e DJANGO_SETTINGS_MODULE=django_scaffold.settings_test -it umbrella-worker-1 pytest --cov=./ --cov-report=xml:coverage.xml --junitxml=junit.xml -o junit_family=legacy --rootdir=/app -c pytest.ini $(EXTRA_PYTEST_ARGS)

.PHONY: devenv.upload.worker
devenv.upload.worker:
	./tools/devenv/scripts/codecovcli-helper.sh upload-process -f apps/worker/coverage.xml --disable-search -F workerunit --recurse-submodules --plugin noop
	./tools/devenv/scripts/codecovcli-helper.sh upload-process --report-type test_results -f apps/worker/junit.xml --disable-search -F workerunit --recurse-submodules --plugin noop

.PHONY: devenv.test.api
devenv.test.api:
	docker exec -e COVERAGE_CORE=sysmon -e RUN_ENV=TESTING -e CODECOV_YML=${TEST_YML} -e DJANGO_SETTINGS_MODULE=codecov.settings_test -it umbrella-api-1 pytest --cov=./ --cov-report=xml:coverage.xml --junitxml=junit.xml -o junit_family=legacy --rootdir=/app -c pytest.ini $(EXTRA_PYTEST_ARGS)

.PHONY: devenv.upload.api
devenv.upload.api:
	./tools/devenv/scripts/codecovcli-helper.sh upload-process -f apps/codecov-api/coverage.xml --disable-search -F apiunit --recurse-submodules --plugin noop
	./tools/devenv/scripts/codecovcli-helper.sh upload-process --report-type test_results -f apps/codecov-api/junit.xml --disable-search -F apiunit --recurse-submodules --plugin noop

.PHONY: devenv.test.shared
devenv.test.shared:
	docker exec -e COVERAGE_CORE=sysmon -e RUN_ENV=TESTING -e CODECOV_YML=${TEST_YML} -e DJANGO_SETTINGS_MODULE=shared.django_apps.settings_test -it umbrella-shared-1 pytest --cov ./shared --cov-report=xml:tests/coverage.xml --junitxml=tests/junit.xml -o junit_family=legacy --rootdir=/app -c pytest.ini $(EXTRA_PYTEST_ARGS)

.PHONY: devenv.upload.shared
devenv.upload.shared:
	./tools/devenv/scripts/codecovcli-helper.sh upload-process -f libs/shared/tests/coverage.xml --disable-search -F sharedunit --recurse-submodules --plugin noop
	./tools/devenv/scripts/codecovcli-helper.sh upload-process --report-type test_results -f libs/shared/tests/junit.xml --disable-search -F sharedunit --recurse-submodules --plugin noop
