# Generated by Django 4.2.20 on 2025-07-03 20:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("legacy_migrations", "0008_delete_pull_update_trigger"),
    ]

    operations = [
        migrations.DeleteModel(
            name="YamlHistory",
        ),
    ]
