# Generated by Django 4.2.21 on 2025-06-02 17:56

from django.db import migrations


def update_version(apps, schema):
    Constants = apps.get_model("core", "Constants")
    version = Constants.objects.get(key="version")
    version.value = "25.6.2"
    version.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0069_increment_version"),
    ]

    operations = [migrations.RunPython(update_version)]
