# Generated by Django 4.2.21 on 2025-06-10 00:40

from django.db import migrations, models

from shared.django_apps.migration_utils import RiskyAddField


class Migration(migrations.Migration):
    """
    ALTER TABLE pulls ADD COLUMN sentry_commentid TEXT NULL;
    """

    dependencies = [
        ("core", "0070_increment_version"),
    ]

    operations = [
        RiskyAddField(
            model_name="pull",
            name="sentry_commentid",
            field=models.TextField(null=True),
        ),
    ]
