# Generated by Django 4.2.21 on 2025-07-09 15:04

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("core", "0071_pull_sentry_commentid"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="pull",
            index=models.Index(fields=["-pullid"], name="pulls_pullid_desc"),
        ),
    ]
