# Generated by Django 4.2.21 on 2025-07-08 20:38

from django.db import migrations


def update_version(apps, schema):
    Constants = apps.get_model("core", "Constants")
    version = Constants.objects.get(key="version")
    version.value = "25.7.7"
    version.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0072_pull_pulls_pullid_desc"),
    ]

    operations = [migrations.RunPython(update_version)]
