# syntax=docker/dockerfile:1.4
ARG REQUIREMENTS_IMAGE

FROM $REQUIREMENTS_IMAGE as test_reqs

ENV UV_LINK_MODE=copy \
    UV_COMPILE_BYTECODE=1 \
    UV_PYTHON_DOWNLOADS=never \
    UV_PROJECT_ENVIRONMENT=/app

RUN apt-get update
RUN apt-get install -y git build-essential netcat-traditional
RUN git config --global --add safe.directory /app || true

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=./pyproject.toml,target=./pyproject.toml \
    --mount=type=bind,source=./uv.lock,target=./uv.lock \
    --mount=type=bind,source=libs/shared,target=libs/shared \
    uv pip install --group dev --system
