setup:
  codecov_url: https://codecov.io
  debug: no
  loglvl: INFO
  encryption_secret: "zp^P9*i8aR3"
  okta:
    iss: "https://example.okta.com"
  http:
    force_https: yes
    cookie_secret: abc123
    timeouts:
      connect: 10
      receive: 15
  tasks:
    celery:
      soft_timelimit: 200
      hard_timelimit: 240
    upload:
      queue: uploads
  cache:
    yaml: 600 # 10 minutes
    tree: 600 # 10 minutes
    diff: 300 # 5 minutes
    chunks: 300 # 5 minutes
    uploads: 86400 # 1 day

services:
  database_url: postgres://postgres:password@postgres:5432/postgres
  timeseries_database_url: postgres://postgres:password@timescale:5432/postgres
  redis_url: redis://redis:6379
  minio:
    hash_key: testixik8qdauiab1yiffydimvi72ekq # never change this
    periodic_callback_ms: false
    access_key_id: codecov-default-key
    secret_access_key: codecov-default-secret
    verify_ssl: false

github:
  bot:
    username: codecov-io
  integration:
    id: 254
    pem: src/certs/github.pem

bitbucket:
  bot:
    username: codecov-io

# Bitbucket Data Center (Server) configuration
# bitbucket_server:
#   url: https://your-bitbucket-server.company.com          # Base URL of your Bitbucket Data Center
#   client_id: your-oauth-client-id                         # OAuth Client ID from Application Link
#   client_secret: your-oauth-client-secret                 # OAuth Client Secret from Application Link
#   bot:
#     key: your-bot-personal-access-token                   # Bot personal access token
#   bots:
#     tokenless:
#       key: your-tokenless-bot-token                       # Tokenless bot access token
#   oauth2:
#     enabled: true                                         # Enable OAuth 2.0 (default: false)
#     use_pkce: true                                        # Enable PKCE for security (default: true)
#     pkce_code_challenge_method: S256                      # PKCE method: S256 or plain (default: S256)
#     user_avatar_size: 48                                  # User avatar size in pixels (default: 48)

gitlab:
  bot:
    username: codecov-io

site:
  codecov:
    require_ci_to_pass: yes

  coverage:
    precision: 2
    round: down
    range: "70...100"

    status:
      project: yes
      patch: yes
      changes: no

  parsers:
    gcov:
      branch_detection:
        conditional: yes
        loop: yes
        method: no
        macro: no

    javascript:
      enable_partials: no

  comment:
    layout: "reach, diff, flags, files, footer"
    behavior: default
    require_changes: no
    require_base: no
    require_head: yes
