# Generated by Django 4.2.16 on 2025-05-01 23:27

from django.db import migrations, models

from shared.django_apps.migration_utils import RiskyAlterField

"""
BEGIN;
--
-- Alter field id on testflagbridge
--
ALTER TABLE "reports_test_results_flag_bridge" ALTER COLUMN "id" TYPE bigint USING "id"::bigint;
COMMIT;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0041_rm_reportdetails"),
    ]

    operations = [
        RiskyAlterField(
            model_name="testflagbridge",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
