# Generated by Django 4.2.20 on 2025-07-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staticanalysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staticanalysissinglefilesnapshot",
            name="state_id",
            field=models.IntegerField(
                choices=[(1, "CREATED"), (2, "VALID"), (3, "REJECTED")]
            ),
        ),
        migrations.AlterModelTable(
            name="staticanalysissinglefilesnapshot",
            table="staticanalysis_staticanalysissinglefilesnapshot",
        ),
        migrations.AlterModelTable(
            name="staticanalysissuite",
            table="staticanalysis_staticanalysissuite",
        ),
        migrations.AlterModelTable(
            name="staticanalysissuitefilepath",
            table="staticanalysis_staticanalysissuitefilepath",
        ),
    ]
