# Generated by Django 4.2.16 on 2025-04-25 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ta_timeseries", "0005_testrun_real_time_agg"),
    ]

    operations = [
        migrations.RunSQL(
            "select remove_continuous_aggregate_policy('ta_timeseries_testrun_summary_1day');"
        ),
        migrations.RunSQL(
            "select remove_continuous_aggregate_policy('ta_timeseries_testrun_branch_summary_1day');"
        ),
        migrations.RunSQL(
            """
            select add_continuous_aggregate_policy(
                'ta_timeseries_testrun_summary_1day',
                start_offset => '7 days',
                end_offset => '1 second',
                schedule_interval => INTERVAL '1 days'
            );
            """,
            reverse_sql="select remove_continuous_aggregate_policy('ta_timeseries_testrun_summary_1day');",
        ),
        migrations.RunSQL(
            """
            select add_continuous_aggregate_policy(
                'ta_timeseries_testrun_branch_summary_1day',
                start_offset => '7 days',
                end_offset => '1 second',
                schedule_interval => INTERVAL '1 days'
            );
            """,
            reverse_sql="select remove_continuous_aggregate_policy('ta_timeseries_testrun_branch_summary_1day');",
        ),
    ]
