# Generated by Django 4.2.20 on 2025-05-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ta_timeseries", "0006_auto_20250425_1925"),
    ]

    operations = [
        migrations.AddField(
            model_name="testrun",
            name="properties",
            field=models.JSONField(null=True),
        ),
    ]
