# Generated by Django 4.2.20 on 2025-05-06 20:09

from django.db import migrations

from shared.django_apps.migration_utils import RiskyRunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("ta_timeseries", "0007_add_properties"),
    ]

    operations = [
        RiskyRunSQL(
            """
            delete from
            ta_timeseries_testrun
            where length(testsuite) > 1000
                or length(classname) > 1000
                or length(name) > 1000
                or length(computed_name) > 1000
                or length(filename) > 1000;
            """
        )
    ]
