# Generated by Django 4.2.20 on 2025-05-12 15:55

from django.db import migrations, models

from shared.django_apps.migration_utils import RiskyAddIndex


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("ta_timeseries", "0008_auto_20250506_2009"),
    ]

    operations = [
        RiskyAddIndex(
            model_name="testrun",
            index=models.Index(fields=["upload_id", "outcome"], name="ta_ts__upload_i"),
        ),
    ]
