# Generated by Django 4.2.20 on 2025-05-28 15:40

from django.db import migrations

from shared.django_apps.migration_utils import RiskyRunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("ta_timeseries", "0009_testrun_ta_ts__upload_i"),
    ]

    operations = [
        RiskyRunSQL(
            """
            DO $$
            DECLARE
                index_name text;
            BEGIN
                FOR index_name IN
                    SELECT indexname 
                    FROM pg_indexes 
                    JOIN timescaledb_information.continuous_aggregates
                    ON continuous_aggregates.materialization_hypertable_schema = pg_indexes.schemaname
                    AND continuous_aggregates.materialization_hypertable_name = pg_indexes.tablename
                    WHERE view_name = 'ta_timeseries_testrun_summary_1day'
                LOOP
                    EXECUTE 'DROP INDEX IF EXISTS ' || quote_ident(index_name);
                END LOOP;
            END $$;
            """
        ),
        RiskyRunSQL(
            """
            DO $$
            DECLARE
                index_name text;
            BEGIN
                FOR index_name IN
                    SELECT indexname 
                    FROM pg_indexes 
                    JOIN timescaledb_information.continuous_aggregates
                    ON continuous_aggregates.materialization_hypertable_schema = pg_indexes.schemaname
                    AND continuous_aggregates.materialization_hypertable_name = pg_indexes.tablename
                    WHERE view_name = 'ta_timeseries_testrun_branch_summary_1day'
                LOOP
                    EXECUTE 'DROP INDEX IF EXISTS ' || quote_ident(index_name);
                END LOOP;
            END $$;
            """
        ),
    ]
