# Generated by Django 4.2.20 on 2025-01-XX XX:XX

from django.db import migrations

from shared.django_apps.migration_utils import RiskyRunSQL


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("ta_timeseries", "0014_set_cagg_chunk_interval"),
    ]
    operations = [
        RiskyRunSQL(
            """
            DROP INDEX IF EXISTS _timescaledb_internal._materialized_hypertable_3_timestamp_bin_idx;
            """
        ),
        RiskyRunSQL(
            """
            DROP INDEX IF EXISTS _timescaledb_internal._materialized_hypertable_3_repo_id_timestamp_bin_idx;
            """
        ),
        RiskyRunSQL(
            """
            DROP INDEX IF EXISTS _timescaledb_internal._materialized_hypertable_3_branch_timestamp_bin_idx;
            """
        ),
        RiskyRunSQL(
            """
            DROP INDEX IF EXISTS _timescaledb_internal._materialized_hypertable_3_testsuite_timestamp_bin_idx;
            """
        ),
        RiskyRunSQL(
            """
            DROP INDEX IF EXISTS _timescaledb_internal._materialized_hypertable_3_classname_timestamp_bin_idx;
            """
        ),
        RiskyRunSQL(
            """
            DROP INDEX IF EXISTS _timescaledb_internal._materialized_hypertable_3_name_timestamp_bin_idx;
            """
        ),
        RiskyRunSQL(
            """
            DROP INDEX IF EXISTS _timescaledb_internal._materialized_hypertable_2_timestamp_bin_idx;
            """
        ),
        RiskyRunSQL(
            """
            DROP INDEX IF EXISTS _timescaledb_internal._materialized_hypertable_2_repo_id_timestamp_bin_idx;
            """
        ),
        RiskyRunSQL(
            """
            DROP INDEX IF EXISTS _timescaledb_internal._materialized_hypertable_2_testsuite_timestamp_bin_idx;
            """
        ),
        RiskyRunSQL(
            """
            DROP INDEX IF EXISTS _timescaledb_internal._materialized_hypertable_2_classname_timestamp_bin_idx;
            """
        ),
        RiskyRunSQL(
            """
            DROP INDEX IF EXISTS _timescaledb_internal._materialized_hypertable_2_name_timestamp_bin_idx;
            """
        ),
    ]
