# Generated by Django 4.2.20 on 2025-07-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ta_timeseries", "0015_drop_materialized_hypertable_indexes"),
    ]

    operations = [
        # Bringing the state in sync with the changes made manually with migration 0011
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER INDEX IF EXISTS ta_ts_upload_id_outcome_test_id_idx RENAME TO ta_ts_upload_outcome_test_idx;
                    """
                ),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name="testrun",
                    name="ta_ts__branch_i",
                ),
                migrations.RemoveIndex(
                    model_name="testrun",
                    name="ta_ts__test_i",
                ),
                migrations.AddIndex(
                    model_name="testrun",
                    index=models.Index(
                        fields=["upload_id", "outcome", "test_id"],
                        name="ta_ts_upload_outcome_test_idx",
                    ),
                ),
            ],
        ),
    ]
