# Generated by Django 4.2.21 on 2025-07-17 17:05

from django.db import migrations, models

from shared.django_apps.migration_utils import RiskyAddIndex


class Migration(migrations.Migration):
    dependencies = [
        (
            "ta_timeseries",
            "0020_aggregatedaily_aggregatehourly_branchaggregatedaily_and_more",
        ),
    ]

    operations = [
        RiskyAddIndex(
            model_name="testrun",
            index=models.Index(
                fields=["repo_id", "timestamp"], name="ta_ts__repo_timestamp_idx"
            ),
        ),
        RiskyAddIndex(
            model_name="testrun",
            index=models.Index(
                fields=["repo_id", "branch", "timestamp"],
                name="ta_ts__repo_branch_time_idx",
            ),
        ),
    ]
