# Generated by Django 4.2.20 on 2025-07-02 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("compare", "0006_componentcomparison_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="commitcomparison",
            table="compare_commitcomparison",
        ),
        migrations.AlterModelTable(
            name="componentcomparison",
            table="compare_componentcomparison",
        ),
        migrations.AlterModelTable(
            name="flagcomparison",
            table="compare_flagcomparison",
        ),
    ]
