# Generated by Django 4.2.20 on 2025-07-02 14:34

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import psqlextra.backend.migrations.operations.add_default_partition
import psqlextra.backend.migrations.operations.create_partitioned_model
import psqlextra.manager.manager
import psqlextra.models.partitioned
import psqlextra.types
from django.db import migrations, models

import shared.django_apps.upload_breadcrumbs.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        psqlextra.backend.migrations.operations.create_partitioned_model.PostgresCreatePartitionedModel(
            name="UploadBreadcrumb",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("commit_sha", models.TextField()),
                ("repo_id", models.BigIntegerField()),
                (
                    "upload_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.BigIntegerField(),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("sentry_trace_id", models.TextField(blank=True, null=True)),
                (
                    "breadcrumb_data",
                    models.JSONField(
                        help_text="Variable breadcrumb data for a given upload",
                        validators=[
                            shared.django_apps.upload_breadcrumbs.models.BreadcrumbData.django_validate
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["commit_sha"], name="upload_breadcrumbs_commit_sha"
                    ),
                    models.Index(
                        fields=["commit_sha", "repo_id"],
                        name="upload_breadcrumbs_sha_repo",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["upload_ids"], name="upload_breadcrumbs_upload_ids"
                    ),
                ],
            },
            partitioning_options={
                "method": psqlextra.types.PostgresPartitioningMethod["RANGE"],
                "key": ["created_at"],
            },
            bases=(psqlextra.models.partitioned.PostgresPartitionedModel,),
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        psqlextra.backend.migrations.operations.add_default_partition.PostgresAddDefaultPartition(
            model_name="UploadBreadcrumb",
            name="default",
        ),
    ]
